local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.find_files, {})
vim.keymap.set('n', '<leader>fg', builtin.git_files, {})
vim.keymap.set('n', '<leader>gg', function()
	builtin.live_grep({})
end)
vim.keymap.set('n', '<leader>gs', function()
	builtin.grep_string({})
end)
